# Generated by Django 6.0.2 on 2026-02-28 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.TextField(default='TEmp'),
            preserve_default=False,
        ),
    ]
