# Generated by Django 6.0.2 on 2026-03-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='d2x_id',
            field=models.IntegerField(unique=True),
        ),
    ]
