# Generated by Django 6.0.2 on 2026-02-16 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('nicknames', models.JSONField(blank=True, default=list)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
