# Generated by Django 6.0.2 on 2026-03-14 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('talent', '0002_alter_character_voice_actor'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('score', models.FloatField(default=0.0)),
                ('users', models.IntegerField(default=0)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('summary', models.TextField(default='A synopsis will be written later.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trailer_url', models.URLField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Announced'), (1, 'In Production'), (2, 'Released'), (3, 'End of Service'), (4, 'Cancelled')], default=0)),
                ('esrb_rating', models.IntegerField(choices=[(0, 'Everyone'), (1, 'Everyone 10+'), (2, 'Teen'), (3, 'Mature 17+'), (4, 'Adults Only 18+'), (5, 'Rating Pending'), (6, 'Rating Pending (Likely Mature)')], default=5)),
                ('pegi_rating', models.IntegerField(choices=[(0, 'PEGI 3'), (1, 'PEGI 7'), (2, 'PEGI 12'), (3, 'PEGI 16'), (4, 'PEGI 18'), (5, 'Rating Pending')], default=5)),
                ('steam_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('franchise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.franchise')),
                ('genres', models.ManyToManyField(blank=True, related_name='games', to='base.genre')),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='DLC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('score', models.FloatField(default=0.0)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asobu.game')),
            ],
        ),
        migrations.CreateModel(
            name='GameCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_playable', models.BooleanField(default=False)),
                ('role', models.IntegerField(choices=[(0, 'Main'), (1, 'Supporting')], default=1)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talent.character')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asobu.game')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='characters',
            field=models.ManyToManyField(related_name='games', through='asobu.GameCharacter', to='talent.character'),
        ),
        migrations.AddField(
            model_name='game',
            name='developers',
            field=models.ManyToManyField(blank=True, null=True, related_name='developed_games', to='asobu.gamecompany'),
        ),
        migrations.AddField(
            model_name='game',
            name='publishers',
            field=models.ManyToManyField(blank=True, null=True, related_name='published_games', to='asobu.gamecompany'),
        ),
        migrations.CreateModel(
            name='GameRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('series_entry', 'Series Entry'), ('re_release', 'Rerelease')], default='series_entry')),
                ('from_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_predeccessor', to='asobu.game')),
                ('to_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_sucessor', to='asobu.game')),
            ],
        ),
        migrations.CreateModel(
            name='GamePlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateField(null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asobu.game')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asobu.platform')),
            ],
            options={
                'ordering': ['release_date'],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='platforms',
            field=models.ManyToManyField(related_name='released_games', through='asobu.GamePlatform', to='asobu.platform'),
        ),
        migrations.AddField(
            model_name='game',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tagged_games', to='asobu.tag'),
        ),
        migrations.AddIndex(
            model_name='gamecharacter',
            index=models.Index(fields=['game'], name='asobu_gamec_game_id_1b7bed_idx'),
        ),
        migrations.AddConstraint(
            model_name='gamecharacter',
            constraint=models.UniqueConstraint(fields=('game', 'character'), name='unique_game_character'),
        ),
        migrations.AddConstraint(
            model_name='gameplatform',
            constraint=models.UniqueConstraint(fields=('game', 'platform'), name='unique_game_platform'),
        ),
    ]
