# Generated by Django 6.0.2 on 2026-04-19 08:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asobu', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Playing'), (1, 'Completed'), (2, 'Plan To Play'), (3, 'On Hold'), (4, 'Replaying')], default=0)),
                ('score', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('note', models.CharField(blank=True, max_length=256, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('start_play_date', models.DateField(blank=True, null=True)),
                ('end_play_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asobu.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_list', to='users.arcadiauser')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['status'], name='asobu_gamel_status_ba5dc8_idx')],
                'unique_together': {('user', 'game')},
            },
        ),
    ]
