# Generated by Django 6.0.2 on 2026-07-01 23:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asobu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='funny_count',
        ),
        migrations.RemoveField(
            model_name='review',
            name='helpful_count',
        ),
        migrations.RemoveField(
            model_name='review',
            name='nice_count',
        ),
        migrations.AddField(
            model_name='review',
            name='dislike_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='like_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='score',
            field=models.FloatField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(default='A review will be written later'),
        ),
    ]
