# Generated by Django 6.0.2 on 2026-06-08 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asobu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='bg_image_path',
        ),
    ]
