# Generated by Django 6.0.2 on 2026-06-25 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asobu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='banner_image_url',
        ),
        migrations.RemoveField(
            model_name='game',
            name='bg_image_url',
        ),
        migrations.RemoveField(
            model_name='game',
            name='cover_image_url',
        ),
    ]
