# Generated by Django 6.0.2 on 2026-05-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asobu', '0002_gamelistentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelistentry',
            name='is_private',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
