# Generated by Django 6.0.2 on 2026-05-09 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asobu', '0002_gamelistentry_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='bg_image_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
