# Generated by Django 6.0.2 on 2026-05-05 20:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asobu', '0002_gamelistentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelistentry',
            name='is_private',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='gamelistentry',
            name='review_updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
