# Generated by Django 6.0.2 on 2026-02-26 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('bio', models.TextField(blank=True, default='A bio will be written later')),
                ('socials', models.JSONField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('bio', models.TextField(blank=True, default='A bio will be written later')),
                ('socials', models.JSONField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('special_message', models.TextField(blank=True, null=True)),
                ('character', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artist_profile', to='characters.character')),
                ('voice_actor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artist_profile', to='talent.voiceactor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
