# Generated by Django 6.0.2 on 2026-06-08 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='cover_img_url',
            new_name='cover_image_url',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='cover_img_url',
            new_name='cover_image_url',
        ),
        migrations.RenameField(
            model_name='voiceactor',
            old_name='cover_img_url',
            new_name='cover_image_url',
        ),
    ]
