# Generated by Django 6.0.2 on 2026-03-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0002_alter_character_voice_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='cover_img_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='cover_img_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voiceactor',
            name='cover_img_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
