# Generated by Django 6.0.2 on 2026-03-19 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('talent', '0002_alter_character_voice_actor'),
        ('users', '0003_alter_user_d2x_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('score', models.FloatField(default=0.0)),
                ('users', models.IntegerField(default=0)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('summary', models.TextField(default='A synopsis will be written later.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title_native', models.CharField(blank=True, help_text='The origin way to write the anime', max_length=255, null=True)),
                ('title_romaji', models.CharField(blank=True, help_text='How to pronounce the name with the english alphabet', max_length=255, null=True)),
                ('other_titles', models.JSONField(blank=True, default=[], help_text='Ways to call the anime part from Japanese and English', null=True)),
                ('season', models.IntegerField(blank=True, choices=[(0, 'Winter'), (1, 'Spring'), (2, 'Summer'), (3, 'Fall')], default=None, null=True)),
                ('season_year', models.SmallIntegerField(blank=True, null=True)),
                ('type', models.IntegerField(choices=[(0, 'Tv'), (1, 'Movie'), (2, 'Ova'), (3, 'Ona'), (4, 'Web')], default=0)),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Not yet aired'), (1, 'Airing'), (2, 'Finished airing'), (3, 'Delayed'), (4, 'Cancelled')], default=0)),
                ('rating', models.IntegerField(choices=[(0, 'Not yet rated'), (1, 'All ages'), (2, 'Children'), (3, 'Teens 13 or older'), (4, '17+ (Violence/Profanity)')], default=0)),
                ('episode_count', models.SmallIntegerField(blank=True, null=True)),
                ('hashtag', models.CharField(blank=True, max_length=128, null=True)),
                ('banner_img_url', models.URLField(blank=True, null=True)),
                ('cover_img_url', models.URLField(blank=True, null=True)),
                ('airing_start_date', models.DateField(blank=True, null=True)),
                ('airing_end_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('franchise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.franchise')),
                ('genres', models.ManyToManyField(blank=True, related_name='animes', to='base.genre')),
                ('next_anime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_previous_anime', to='miru.anime')),
                ('prev_anime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_next_anime', to='miru.anime')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='AnimeCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AniListData',
            fields=[
                ('anime', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='miru.anime')),
                ('anilist_id', models.IntegerField()),
                ('rank_score', models.SmallIntegerField(blank=True, null=True)),
                ('rank_popular', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnimeCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(blank=True, choices=[(0, 'Main'), (1, 'Supporting')], default=1)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast', to='miru.anime')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talent.character')),
            ],
            options={
                'unique_together': {('anime', 'character')},
            },
        ),
        migrations.AddField(
            model_name='anime',
            name='characters',
            field=models.ManyToManyField(blank=True, related_name='animes', through='miru.AnimeCharacter', to='talent.character'),
        ),
        migrations.AddField(
            model_name='anime',
            name='producer',
            field=models.ManyToManyField(blank=True, null=True, related_name='produced_animes', to='miru.animecompany'),
        ),
        migrations.AddField(
            model_name='anime',
            name='studio',
            field=models.ManyToManyField(blank=True, null=True, related_name='studio_animes', to='miru.animecompany'),
        ),
        migrations.CreateModel(
            name='AnimeEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(default='A description will be written later')),
                ('url', models.URLField(blank=True, null=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='miru.anime')),
            ],
            options={
                'ordering': ['anime', 'number'],
            },
        ),
        migrations.CreateModel(
            name='RelatedAnime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(blank=True, choices=[('spinoff', 'Spin-off'), ('side_story', 'Side Story'), ('alternative_version', 'Alternative Version'), ('other', 'Other')], default='other')),
                ('node_anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_anime', to='miru.anime')),
                ('source_anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_anime', to='miru.anime')),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='related_anime',
            field=models.ManyToManyField(blank=True, related_name='related_to_anime', through='miru.RelatedAnime', to='miru.anime'),
        ),
        migrations.CreateModel(
            name='AnimeListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Watching'), (1, 'Completed'), (2, 'Plan To Watch'), (3, 'On Hold')], default=0)),
                ('current_episode', models.SmallIntegerField(blank=True, default=0)),
                ('score', models.FloatField(blank=True, null=True)),
                ('start_watch_date', models.DateField(blank=True, null=True)),
                ('end_watch_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miru.anime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='miru_animel_user_id_970265_idx'), models.Index(fields=['anime'], name='miru_animel_anime_i_0e6840_idx'), models.Index(fields=['status'], name='miru_animel_status_9c0e2f_idx'), models.Index(fields=['user', 'status'], name='miru_animel_user_id_4279d7_idx')],
                'unique_together': {('user', 'anime')},
            },
        ),
    ]
