# Generated by Django 6.0.2 on 2026-02-17 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(blank=True, choices=[(0, 'Winter'), (1, 'Spring'), (2, 'Summer'), (3, 'Fall')], null=True)),
                ('year', models.IntegerField(blank=True, default=2000)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('score', models.FloatField(default=0.0)),
                ('users', models.IntegerField(default=0)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('summary', models.TextField(default='A synopsis will be written later.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_ja', models.CharField(blank=True, max_length=255, null=True)),
                ('title_romaji', models.CharField(blank=True, max_length=255, null=True)),
                ('title_alternatives', models.JSONField(blank=True, default=list)),
                ('status', models.IntegerField(choices=[(0, 'Not yet aired'), (1, 'Airing'), (2, 'Finished airing')], default=0)),
                ('type', models.IntegerField(choices=[(0, 'Tv'), (1, 'Movie'), (2, 'OVA'), (3, 'ONA'), (4, 'Web')], default=0)),
                ('rating', models.IntegerField(blank=True, choices=[(0, 'All ages'), (1, 'Children'), (2, 'Teens 13 or older'), (3, '17+ (Violence/Profanity)')], default=0)),
                ('airing_start_date', models.DateField(blank=True, null=True)),
                ('airing_end_date', models.DateField(blank=True, null=True)),
                ('franchise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.franchise')),
                ('genres', models.ManyToManyField(blank=True, related_name='animes', to='base.genre')),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='AnimeCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(blank=True, choices=[(0, 'Main'), (1, 'Supporting')], default=1)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miru.anime')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='characters',
            field=models.ManyToManyField(blank=True, related_name='animes', through='miru.AnimeCharacter', to='characters.character'),
        ),
        migrations.CreateModel(
            name='AnimeRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(blank=True, choices=[('series_entry', 'Series Entry'), ('spinoff', 'Spin-off'), ('side_story', 'Side Story'), ('alternataive_version', 'Alternate'), ('other', 'Other')], default='other')),
                ('from_anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_to', to='miru.anime')),
                ('to_anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_from', to='miru.anime')),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='related',
            field=models.ManyToManyField(blank=True, related_name='related_anime', through='miru.AnimeRelation', to='miru.anime'),
        ),
        migrations.AddField(
            model_name='anime',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='miru.season'),
        ),
        migrations.AddField(
            model_name='anime',
            name='studio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='miru.studio'),
        ),
    ]
