# Generated by Django 6.0.2 on 2026-06-08 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miru', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='banner_img_url',
            new_name='banner_image_url',
        ),
        migrations.RenameField(
            model_name='anime',
            old_name='cover_img_url',
            new_name='cover_image_url',
        ),
    ]
