# Generated by Django 6.0.2 on 2026-03-03 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miru', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(default='A description will be written later')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miru.anime')),
            ],
            options={
                'ordering': ['anime', 'number'],
            },
        ),
    ]
