# Generated by Django 6.0.2 on 2026-02-24 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miru', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Watching'), (1, 'Completed'), (2, 'Plan To Watch'), (3, 'On Hold')], default=0)),
                ('current_episode', models.SmallIntegerField(blank=True, default=0)),
                ('score', models.FloatField(blank=True, null=True)),
                ('start_watch_date', models.DateField(blank=True, null=True)),
                ('end_watch_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miru.anime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='miru_animel_user_id_970265_idx'), models.Index(fields=['anime'], name='miru_animel_anime_i_0e6840_idx'), models.Index(fields=['status'], name='miru_animel_status_9c0e2f_idx'), models.Index(fields=['user', 'status'], name='miru_animel_user_id_4279d7_idx')],
                'unique_together': {('user', 'anime')},
            },
        ),
    ]
