# Generated by Django 6.0.2 on 2026-03-19 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miru', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animeepisode',
            name='cover_img_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
