# Generated by Django 6.0.2 on 2026-03-28 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miru', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyAnimeListData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mal_id', models.IntegerField(unique=True)),
                ('rank_score', models.SmallIntegerField(blank=True, null=True)),
                ('rank_popular', models.SmallIntegerField(blank=True, null=True)),
                ('anime', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='miru.anime')),
            ],
        ),
    ]
