# Generated by Django 6.0.2 on 2026-06-25 04:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miru', '0002_rename_cover_img_url_animeepisode_cover_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animelistentry',
            name='score',
        ),
        migrations.CreateModel(
            name='AnimeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.IntegerField(db_index=True)),
                ('score', models.FloatField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('text', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('like_count', models.IntegerField(blank=True, default=0)),
                ('dislike_count', models.IntegerField(blank=True, default=0)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miru.anime')),
            ],
            options={
                'unique_together': {('profile_id', 'anime')},
            },
        ),
    ]
