# Generated by Django 6.0.2 on 2026-06-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miru', '0002_rename_banner_img_url_anime_banner_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='bg_image_path',
        ),
        migrations.AddField(
            model_name='anime',
            name='bg_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
