# Generated by Django 6.0.2 on 2026-06-28 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miru', '0003_remove_animelistentry_score_animereview'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteAnime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.IntegerField(db_index=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='miru.anime')),
            ],
            options={
                'unique_together': {('profile_id', 'anime')},
            },
        ),
    ]
