# Generated by Django 6.0.2 on 2026-06-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miru', '0004_favoriteanime'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomAnimeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=False)),
                ('profile_id', models.IntegerField(db_index=True)),
                ('title', models.CharField(blank=True, max_length=125)),
                ('anime', models.ManyToManyField(related_name='custom_list_appearance', to='miru.anime')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
