# Generated by Django 6.0.2 on 2026-07-01 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miru', '0005_customanimelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animereview',
            name='text',
            field=models.TextField(default='A review will be written later'),
        ),
    ]
